server.port=9090

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

logging:
level:
ru.practicum.shareit: INFO
ru.practicum.shareit.item.ItemServiceImpl: INFO

#---
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://155.212.166.137:5433/later
spring.datasource.username=mydbuser
spring.datasource.password=MyDbUser123!
#---
spring.config.activate.on-profile=test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:postgresql://155.212.166.137:5433/later
spring.datasource.username=mydbuser
spring.datasource.password=MyDbUser123!